# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Admin\Desktop\Python_Script\HelloWorld.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from Calculator import *

def LCD_display(self,MainWindow,value):
    self.lcdNumber.setProperty("value", value)
def button_clicked(self):
    value=2
    self.LCD_display(MainWindow,value)
    self.pushButton_2.clicked.connect(self.button_clicked)